### ISSUE TITLE
Need help section in app for new users

### ISSUE THREAD

**Issue by syedowaisali** [sufiishq/sufiishq-mobile#39]
**Is your feature request related to a problem? Please describe.**
Right now we don't have any help section for users that will help to understand the app functionality. Therefore, We need a dedicated help screen that could be based on `Text`, `Images` or `Video` so that users can understand the app's functionality.

**Describe the solution you'd like**
- We have an overflow menu item on the top-right in the app bar.
- Add another menu item with the text 'Help`.
- Search `Vector Assets` in Android Studio and use the `ic_round_help_24` round icon from the library.
- Create a new class with the name `HelpView.kt` in this [package](https://github.com/sufiishq/sufiishq-mobile/tree/master/app/src/main/java/pk/sufiishq/app/ui/screen).
- Add the content in the `HelpView` class and make sure the code should be consistent with the app structure.
- Add a new screen in [NavigationHost](https://github.com/sufiishq/sufiishq-mobile/blob/master/app/src/main/java/pk/sufiishq/app/ui/components/NavigationHost.kt) and use [navController](https://github.com/sufiishq/sufiishq-mobile/blob/afc2ee05959a365d6868894e114cb401dec1f2b5/app/src/main/java/pk/sufiishq/app/ui/components/NavigationHost.kt#L29) for navigation.
- Navigate the user to the dedicated help screen.

**Comment by syedowaisali** [comment]
@ffahim007 here is a suggestion, we can also consider web-view for generating the help content. But we need to make sure that performance is our first priority before going on that. Another point, the help section/content could also be divided into groups.

**Comment by syedowaisali** [comment]
**Option 1 with accordions:**

For example:

- Where to find all Kalams.
  - Here we can show an image with text.
- Where to find downloaded Kalam.
  - Here we can show an image with text. 
- How can I download a Kalam.
  - Here we can show an image with text. 
- What is the purpose of favorite Kalam and how can I use this
  - Here we can show an image with text.

**Comment by syedowaisali** [comment]
Here is an important point @ffahim007 Help content should be in some centralized place and the code will generate the help content based on specifications so that in the future we will `add/modify` the content without touching the code.

**Comment by syedowaisali** [comment]
@ffahim007 here is an example template for help.json. Let me know in case you need more assistance on that

| Tag      | Description |
| ----------- | ----------- |
| {image: 'path_of_image'} | path_of_image will be replaced with actual image from assets directory |
| {'divider': 1} | show a divider with provided height |
| {'spacer': 300} | Add a horizontal space between content default no spacing required. |
| \*\*bold** | make the word **bold** |
| \_italic_ | make the word _italic_ |

```JSON
{
    "data": [
        {
            "title": "Accordion Title",
            "content": [
                "some paragraph",
                "{'image': 'help_images/image1.jpg'}",
                "another paragraph",
                "{'divider': 1}",
                "another paragraph",
                "{'spacer': 300}"
                "another paragraph with some **bold** and _italic_ words",
            ]
        }
    ]
}
```

**Comment by syedowaisali** [comment]
https://www.figma.com/file/gvqm74kjZFnFoJsExgRxI9/Untitled?node-id=0%3A1&t=25noPFQHyviROhj2-1

![Help Dark Theme](https://user-images.githubusercontent.com/6067000/211206312-88fb6400-13fb-4a7a-8a56-a2fc91e296c7.png)![Help Light Theme](https://user-images.githubusercontent.com/6067000/211206333-329dc8bf-a721-4b58-bb5f-4de8fe1eaa8d.png)

**Comment by ffahim007** [comment]
Here is the high level implementation details for the help screen

- To read data from JSON I'll be creating a repository/service and all the business logic will be definded in that class
- consume all the functions in helpViewModel
- Then it will work as a data provider for the help screen

![Help Screen](https://user-images.githubusercontent.com/8338379/211757337-86482769-b2a5-48cd-a6f5-26e64a845e97.jpg)

**Comment by syedowaisali** [comment]
@ffahim007 The structure is already implemented in the branch, plz review once get the latest pull, and let me know in case you need any question/clarification

**Comment by ffahim007** [comment]
oh that's great, I'll definitely check and let you know once get the chance.

**Comment by ffahim007** [comment]
@syedowaisali I have noticed all the work is done except the UI part, Right? I have to work on UI part to show the data as per the template

**Comment by syedowaisali** [comment]
https://github.com/sufiishq/sufiishq-mobile/blob/40f7d3c97b2802a951f9a05fd3fd64ce15cd67d9/app/src/main/java/pk/sufiishq/app/core/help/InAppHelpContentResolver.kt#L37-L42

Transformation is also remaining also ignore the color tag we don't need right now that
